image: node:latest
before_script:
  - npm install --global sfdx-cli
stages:
  - validate in UAT
  - deploy in UAT
  - validate in PROD
  - deploy in PROD

validate in UAT:
  stage: validate in UAT
  script:
  - echo "Validation Started in UAT" # Debug statement
  - export MDAPI_DEPLOYDIR=FirstProject/force-app/main/default # Set the metadata deploy directory
  - export INSTANCEURL=https://test.salesforce.com # Set the instance URL for UAT
  - export ALIAS=qa # Set the alias for UAT
  - export TESTLEVEL=RunLocalTests # Set the test level for deployment
  - openssl enc -nosalt -aes-256-cbc -d -in assets/server1.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY_UAT -iv $DECRYPTION_IV_UAT # Decrypt the server key for UAT
  - sfdx force:auth:jwt:grant --instanceurl $INSTANCEURL --clientid $CONSUMER_KEY_UAT --jwtkeyfile assets/server.key --username $USERNAME_UAT --setalias $ALIAS
  - sfdx force:mdapi:deploy --checkonly --wait 10 --deploydir $MDAPI_DEPLOYDIR --targetusername $ALIAS --testlevel $TESTLEVEL # Deploy the metadata to UAT in check-only mode
  - echo "Validation completed in UAT" # Debug statementtt
  only:
    - sub_uat

deploy in UAT:
  stage: deploy in UAT
  script:
  - echo "Deployment Started in UAT" # Debug statement
  - export MDAPI_DEPLOYDIR=FirstProject/force-app/main/default # Set the metadata deploy directory
  - export INSTANCEURL=https://test.salesforce.com # Set the instance URL for UAT
  - export ALIAS=qa # Set the alias for UAT
  - export TESTLEVEL=RunLocalTests # Set the test level for deployment
  - openssl enc -nosalt -aes-256-cbc -d -in assets/server1.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY_UAT -iv $DECRYPTION_IV_UAT # Decrypt the server key for UAT
  - sfdx force:auth:jwt:grant --instanceurl $INSTANCEURL --clientid $CONSUMER_KEY_UAT --jwtkeyfile assets/server.key --username $USERNAME_UAT --setalias $ALIAS # Authenticate to UAT using JWT
  - sfdx force:mdapi:deploy --wait 10 --deploydir $MDAPI_DEPLOYDIR --targetusername $ALIAS --testlevel $TESTLEVEL # Deploy the metadata to UAT in check-only mode
  - echo "Deployment completed in UAT" # Debug statement
  only:
    - main_uat

validate in PROD:
  stage: validate in PROD
  script:
  - echo "Validation Started in UAT" # Debug statement
  - export MDAPI_DEPLOYDIR=FirstProject/force-app/main/default # Set the metadata deploy directory
  - export INSTANCEURL=https://login.salesforce.com # Set the instance URL for prod
  - export ALIAS=qa # Set the alias for prod
  - export TESTLEVEL=RunLocalTests # Set the test level for deployment
  - openssl enc -nosalt -aes-256-cbc -d -in assets/server1.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY_PROD -iv $DECRYPTION_IV_PROD # Decrypt the server key for UAT
  - sfdx force:auth:jwt:grant --instanceurl $INSTANCEURL --clientid $CONSUMER_KEY_PROD --jwtkeyfile assets/server.key --username $USERNAME_PROD --setalias $ALIAS
  - sfdx force:mdapi:deploy --checkonly --wait 10 --deploydir $MDAPI_DEPLOYDIR --targetusername $ALIAS --testlevel $TESTLEVEL # Deploy the metadata to UAT in check-only mode
  - echo "Validation completed in PROD" # Debug statementtt
  only:
    - sub_main

deploy in PROD:
  stage: deploy in PROD
  script:
  - echo "Deployment Started in PROD" # Debug statement
  - export MDAPI_DEPLOYDIR=FirstProject/force-app/main/default # Set the metadata deploy directory
  - export INSTANCEURL=https://login.salesforce.com # Set the instance URL for prod
  - export ALIAS=qa # Set the alias for Prod
  - export TESTLEVEL=RunLocalTests # Set the test level for deployment
  - openssl enc -nosalt -aes-256-cbc -d -in assets/server1.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY_PROD -iv $DECRYPTION_IV_PROD # Decrypt the server key for UAT
  - sfdx force:auth:jwt:grant --instanceurl $INSTANCEURL --clientid $CONSUMER_KEY_PROD --jwtkeyfile assets/server.key --username $USERNAME_PROD --setalias $ALIAS # Authenticate to UAT using JWT
  - sfdx force:mdapi:deploy --wait 10 --deploydir $MDAPI_DEPLOYDIR --targetusername $ALIAS --testlevel $TESTLEVEL # Deploy the metadata to UAT in check-only mode
  - echo "Deployment completed in PROD" # Debug statement
  only:
    - main
